package Recursion.String;
import java.util.ArrayList;
/*
Given a string , WAM to return all its subsequences in an arraylist . A String
is a subsequence of a given String that is generated by deleting some character of a
given string without changing its order.

input : abc
output : a,b,c,ab,bc,ac,abc.
 */
public class Subsequence {
    static ArrayList<String> getSSQ(String s)
    {
        ArrayList<String> ans = new ArrayList<>();
        //base case
        if(s.length()==0)
        {
         ans.add("");
         return ans;
        }
        char a = s.charAt(0);
        ArrayList<String> smallAns = getSSQ(s.substring(1));
        //smallAns [ bc,b,c," ",]
        // ans [bc,abc,b,ab,c,ac,"",a]
        for(String ss : smallAns){
            ans.add(ss);
            ans.add(a + ss);
        }
        return ans;
    }
    static void main(String[] args) {
        String a = "abc";
        System.out.println(getSSQ(a));
    }
}
